POST http://localhost:5000/api/auth/signup
Content-Type: application/json

{
    "firstName": "test firstName",
    "lastName": "test lastName",
    "email": "test2@email",
    "password": "test password"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "test@email",
    "password": "test password"
}

