GET http://localhost:5000/api/jobs

###

GET http://localhost:5000/api/jobs/62c9f2b778a9ce77381dd56a

###

GET http://localhost:5000/api/jobs/search?title=title

###

POST http://localhost:5000/api/jobs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmNjODVlN2M0YWMxNTEwNDdhOGQzM2YiLCJpYXQiOjE2NTc1NzQzMTIsImV4cCI6MTY1NzU3NzkxMn0.3d5lzLZCwXVnEUxVQneEDrD324qoIokJ005Wm9f15jI

{ 
    "title": "title"
    , "companyName": "test company"
    , "city": "test city"
    , "payment": 20
    , "description": "test description"
    , "skills": ["62c9f29178a9ce77381dd569"] 
}

###

PATCH http://localhost:5000/api/jobs/62ca0e8f5b4e193869220767
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmM5ZjViN2Y2N2EwN2YyODRiNWFlZWEiLCJpYXQiOjE2NTc0MDg5MTUsImV4cCI6MTY1NzQxMjUxNX0.KFV1MquuXit2cC5-x6yqK5qL20NTe1-FItDAZJrT_bg

{ 
    "title": "title update"
    , "companyName": "test company update"
    , "city": "test city update"
    , "payment": 30
    , "description": "test description update"
    , "skills": ["62c9f29178a9ce77381dd569"] 
}

###

DELETE http://localhost:5000/api/jobs/62ca0a91fd9b358c0bfa95fb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmM5ZjViN2Y2N2EwN2YyODRiNWFlZWEiLCJpYXQiOjE2NTc0MDgxMjIsImV4cCI6MTY1NzQxMTcyMn0.gbRUM0HbCOyWazSJXOekI3-gqUHPfraMOPH677FnWG4