GET http://localhost:5000/api/jobs

###

GET http://localhost:5000/api/jobs/622d4270635526b98fe2c90b

###

POST http://localhost:5000/api/jobs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmM5ZWNmZWQ0OTVlMTJjMWMxMTU5OGMiLCJpYXQiOjE2NTc0MDA1NzQsImV4cCI6MTY1NzQwNDE3NH0.qIicaPtw2NSBndOWCvM_MSpsnSMrhju-BPwnK4V4yGU

{ 
    "title": "title"
, "companyName": "test company"
, "city": "test city"
, "payment": 20
, "description": "test description"
, "skills": ["62c8b652d512e9bfea6c6a33", "62c8ad8e3201588a60c966fc"] }

