GET http://localhost:5000/api/skills

### 
GET http://localhost:5000/api/skills/62c862f1db055ac1792ba5da

### 

POST http://localhost:5000/api/skills
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmM3NDI2Mzc2NDE1ZmI2OWU3NmJlNTciLCJpYXQiOjE2NTcyMjU4MjcsImV4cCI6MTY1NzIyOTQyN30.RMR6XuD-YAqh6lg67BnEj2vN3eEitfPOPdZpkhlz-1Y

{ "title": "test title" }

###

PATCH http://localhost:5000/api/skills/62c862f1db055ac1792ba5da
Content-Type: application/json

{"title" : "test title update"}