GET http://localhost:5000/api/statistics/62c9f29178a9ce77381dd569

###

POST http://localhost:5000/api/statistics
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmRkZTMxZWU5NTExYjhlNGE0NDM4MjciLCJpYXQiOjE2NTg3Nzk4ODcsImV4cCI6MTY1ODc4MzQ4N30._OiQqRhwfeUJRYtWpUkGkzOHJC2qlmeBE-EiEPFaxOE

{
    "62c9f29178a9ce77381dd569": {
        "_id": "62c9f29178a9ce77381dd569",
        "name": "test 1"
    },
    "62ca1efda520675e265e759b": {
        "_id": "62ca1efda520675e265e759b",
        "name": "test 2"
    },
    "62cc8b519d199f31fb378985": {
        "_id": "62cc8b519d199f31fb378985",
        "name": "test 3"
    }
}

###

POST http://localhost:5000/api/statistics/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmRkZTMxZWU5NTExYjhlNGE0NDM4MjciLCJpYXQiOjE2NTg3Nzk4ODcsImV4cCI6MTY1ODc4MzQ4N30._OiQqRhwfeUJRYtWpUkGkzOHJC2qlmeBE-EiEPFaxOE

{
    "62c9f29178a9ce77381dd569": {
        "_id": "62c9f29178a9ce77381dd569",
        "name": "test 1"
    },
    "62ca1efda520675e265e759b": {
        "_id": "62ca1efda520675e265e759b",
        "name": "test 2"
    },
    "62cc8b519d199f31fb378985": {
        "_id": "62cc8b519d199f31fb378985",
        "name": "test 3"
    }
}

###

PUT http://localhost:5000/api/statistics/62defa6ffd335583a801ad06
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmRkZTMxZWU5NTExYjhlNGE0NDM4MjciLCJpYXQiOjE2NTg3Nzk4ODcsImV4cCI6MTY1ODc4MzQ4N30._OiQqRhwfeUJRYtWpUkGkzOHJC2qlmeBE-EiEPFaxOE

{
    "62c9f29178a9ce77381dd569": {
        "_id": "62c9f29178a9ce77381dd569",
        "name": "test 1"
    },
    "62ca1efda520675e265e759b": {
        "_id": "62ca1efda520675e265e759b",
        "name": "test 2"
    },
    "62cc8b519d199f31fb378985": {
        "_id": "62cc8b519d199f31fb378985",
        "name": "test 3"
    }
}